version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  gasoil:
    image: docker.pkg.github.com/clabroche/docker-registry/gasoil:latest
    hostname: gasoil
    restart: always
    environment:
      PORT: 5472
      mongoDbURL: mongodb://root:passwordtochange@mongodb/gasoil?authSource=admin
    labels:
      com.centurylinklabs.watchtower.enable: "true"

    expose:
      - 5472
    ports:
      - 5472:5472
    links:
      - mongodb
  mongodb:
    image: mongo:4
    hostname: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - 4563:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordtochange
    command: mongod --port 27017
    volumes:
      - ./mongo-volume:/data/db
